config = {}

config.pawncoords = {
    -- ['illegal1'] =      {x =    -1465.49,   y = -186.48,    z = 49.05   },
    -- ['illegal2'] =      {x =    -297.24,    y = 304.35,     z = 90.72   },
    -- ['illegal3'] =      {x =    -333.82,    y = 6228.43,    z = 31.49   },
    ['legal1'] =        {x =    182.8358,     y = -1319.307,     z = 29.31747  },
    ['legal2'] =        {x =    -1279.354,     y = -733.4272,    z = 22.29493   },
    ['lumberjack'] =    {x =    2258.488,     y = 5165.898,     z = 59.11171  },
    ['mining'] =        {x =    232.17,     y = 364.65,     z = 105.97  },
    ['legal3'] =        {x =    412.429,   y = 314.5523,    z = 103.0209   },
}

config.items = 
{
    -- ['stolen10ctchain']     =  {    label = '10ct Gold Chain (p)',                  price = 800,    shop = 'illegal1'   },
    -- ['stolen2ctchain']      =  {    label = '2ct Gold Chain (p)',                   price = 200,    shop = 'illegal1'   },
    -- ['stolen5ctchain']      =  {    label = '5ct Gold Chain (p)',                   price = 400,    shop = 'illegal1'   },
    -- ['stolen8ctchain']      =  {    label = '8ct Gold Chain (p)',                   price = 600,    shop = 'illegal1'   },
    -- ['dragon']              =  {    label = 'Dragon',                               price = 1000,   shop = 'illegal1'   },
    -- ['jadeite']             =  {    label = 'Jadeite Stone',                        price = 300,    shop = 'illegal1'   },
    -- ['mfalcon']             =  {    label = 'Maltese Falcon',                       price = 500,    shop = 'illegal1'   },  
    -- ['marstonrevolver']     =  {    label = 'John Marston\'s Cattleman Revolver',   price = 1500,   shop = 'illegal1'   },
    -- ['dskull']              =  {    label = 'Diamond Skull',                        price = 2000,   shop = 'illegal1'   },
    -- ['stolencasiowatch']    =  {    label = 'Casio Watch (p)',                      price = 200,    shop = 'illegal2'   },
    -- ['stolengameboy']       =  {    label = 'Gameboy (p)',                          price = 250,    shop = 'illegal2'   },
    -- ['stoleniphone']        =  {    label = 'Apple Iphone (p)',                     price = 400,    shop = 'illegal2'   },
    -- ['stolennokia']         =  {    label = 'Nokia Phone (p)',                      price = 400,    shop = 'illegal2'   },
    -- ['stolenoakleys']       =  {    label = 'Oakley Sunglasses (p)',                price = 100,    shop = 'illegal2'   },
    -- ['stolenpixel3']        =  {    label = 'Pixel 3 Phone (p)',                    price = 400,    shop = 'illegal2'   },
    -- ['stolenpsp']           =  {    label = 'PSP (p)',                              price = 500,    shop = 'illegal2'   },
    -- ['stolenraybans']       =  {    label = 'Ray Ban Sunglasses (p)',               price = 100,    shop = 'illegal2'   },
    -- ['stolens8']            =  {    label = 'Samsung S8 (p)',                       price = 400,    shop = 'illegal2'   },
    -- ['wallet']              =  {    label = 'Wallet',                               price = 1500,   shop = 'illegal2'   },
    -- ['maneki']              =  {    label = 'Maneki Neko',                          price = 150,    shop = 'illegal2'   },
    -- ['action']              =  {    label = 'Action Figure',                        price = 150,    shop = 'illegal2'   },
    -- ['antlers']             =  {    label = 'Antlers',                              price = 600,    shop = 'illegal2'   },
    -- ['agothic']             =  {    label = 'American Gothic',                      price = 300,    shop = 'illegal3'   },
    -- ['anime']               =  {    label = 'Anime Poster',                         price = 300,    shop = 'illegal3'   },
    -- ['camille']             =  {    label = 'Camille',                              price = 300,    shop = 'illegal3'   },
    -- ['csuey']               =  {    label = 'Chop Suey',                            price = 300,    shop = 'illegal3'   },
    -- ['doramaar']            =  {    label = 'Dora Maar au Chat',                    price = 300,    shop = 'illegal3'   },
    -- ['femmes']              =  {    label = 'Les Femmes d\'Alger',                  price = 300,    shop = 'illegal3'   },
    -- ['gachet']              =  {    label = 'Portrait of Dr.Gachet',                price = 300,    shop = 'illegal3'   },  
    -- ['monalisa']            =  {    label = 'Mona Lisa',                            price = 1000,   shop = 'illegal3'   },
    -- ['salvator']            =  {    label = 'Salvator Mundi',                       price = 300,    shop = 'illegal3'   }, 
    -- ['salvator']            =  {    label = 'Salvator Mundi',                       price = 300,    shop = 'illegal3'   }, 
    -- ['scream']              =  {    label = 'The Scream',                           price = 300,    shop = 'illegal3'   },
    -- ['sgrace']              =  {    label = 'Saying Grace',                         price = 300,    shop = 'illegal3'   },
    -- ['starrynight']         =  {    label = 'Starry Night',                         price = 300,    shop = 'illegal3'   },
    -- ['telvis']              =  {    label = 'Triple Elvis',                         price = 300,    shop = 'illegal3'   },
    -- ['weeping']             =  {    label = 'Weeping Woman',                        price = 300,    shop = 'illegal3'   },
    -- ['wlilies']             =  {    label = 'Water Lilies',                         price = 300,    shop = 'illegal3'   },
    -- ['zebra']               =  {    label = 'Zebra',                                price = 300,    shop = 'illegal3'   },
    ['diamond']             =  {    label = 'Diamond',                              price = 1000,   shop = 'legal1'     },
	['goldbar']             =  {    label = 'Goldbar',                              price = 1500,   shop = 'legal1'     },
    ['xscondom']            =  {    label = 'Used Condom',                          price = 50,     shop = 'legal2'     },
    ['umbrella']            =  {    label = 'Umbrella',                             price = 150,    shop = 'legal2'     },
    ['swood']               =  {    label = 'Sandal Wood',                          price = 500,    shop = 'lumberjack'     },
	['pwood']               =  {    label = 'Pine wood',                            price = 200,    shop = 'lumberjack'     },
	['owood']               =  {    label = 'Oak wood',                             price = 100,    shop = 'lumberjack'     },
	['bwood']               =  {    label = 'Beach wood',                           price = 70,     shop = 'lumberjack'     },
	['twood']               =  {    label = 'Teak wood',                            price = 50,     shop = 'lumberjack'     },
    ['aluminiumore']        =  {    label = 'Aluminium Ore',                        price = 40,     shop = 'mining'     },
	['copperore']           =  {    label = 'Copper Ore',                           price = 30,     shop = 'mining'     },
	['goldore']             =  {    label = 'Gold Ore',                             price = 250,    shop = 'mining'     },
	['silverore']           =  {    label = 'Silver Ore',                           price = 150,    shop = 'mining'     },
	['diamondore']          =  {    label = 'Diamond Ore',                          price = 800,    shop = 'mining'     },
	['ironore']             =  {    label = 'Iron Ore',                             price = 60,     shop = 'mining'     },
    ['pearl']               =  {    label = 'Pearl',                                price = 1200,   shop = 'legal3'     },
	['faberge']             =  {    label = 'Faberge Egg',                          price = 900,    shop = 'legal3'     },
	['negg']                =  {    label = 'Napoleonic Egg',                       price = 800,    shop = 'legal3'     },
	['pegg']                =  {    label = 'Pink Faberge Egg',                     price = 700,    shop = 'legal3'     },
	['goldcoin']            =  {    label = 'Gold Coin',                            price = 400,    shop = 'legal3'     },
	['silvercoin']          =  {    label = 'Silver Coin',                          price = 250,    shop = 'legal3'     },
}


config.fishes = {

    ['freshwatereel']       =  {label = 'Eel',              price = 40      },
    ['hilsa']               =  {label = 'Hilsa',            price = 40      },
    ['bonito']              =  {label = 'Bonito',           price = 80      },
    ['bassfish']            =  {label = 'Bassfish',         price = 80      },
    ['starfish']            =  {label = 'Starfish',         price = 120      },
    ['squid']               =  {label = 'Squid',            price = 150      },
    ['oceanshell']          =  {label = 'Oceanshell',       price = 250      }    
}

-- config.valuables = {
--     ['rolexwatch']         =  {label = 'Rolex Watch',       price = 750 },
--     ['goldbar']            =  {label = 'Gold Bar',          price = 1000},
--     ['valuablegoods']      =  {label = 'Valuable Goods',    price = 1500},
-- }